---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: devops
  children:
  - name: xld
    type: xldeploy.XLDeployServer
    url: http://localhost:4536
    username: admin
    password: !value "xldeploy_XLDeployServer_xld_password"
  - template: apply
    scheduledStartDate: 2019-11-20T09:00:00+01:00
    phases:
    - phase: DEMO
      tasks:
      - name: Declare Infrastructure
        type: devopsascode.Apply
        server: xld
        content: |-
          ---
          apiVersion: xl-deploy/v1
          kind: Infrastructure
          spec:
          - name: Infrastructure/bmo-xebialabs-france
            type: terraformEnterprise.Organization
            url: https://app.terraform.io
            token: !value "tfe_token"
            deleteWorkspace: true
            children:
            - name: AWSProvider
              type: terraformEnterprise.Provider
              credentials:
                CONFIRM_DESTROY: "1"
                AWS_SECRET_ACCESS_KEY: !value "aws_secret_access_key"
                AWS_ACCESS_KEY_ID: !value "aws_access_key_id"
        values:
          tfe_token: mkjfdmqjmsjfmjdqskmlf
          aws_secret_access_key: abc
          aws_access_key_id: ekyek
        owner: admin
      - name: Create a new Package
        type: devopsascode.Apply
        server: xld
        content: |-
          ---
          apiVersion: xl-deploy/v1
          kind: Applications
          spec:
          - directory: Applications/Corporate
            children:
            - directory: app-foo
              children:
              - name: app-foo-app
                type: udm.Application
                children:
                - name: !value appversion
                  type: udm.DeploymentPackage
                  deployables:
                  - name: myfile
                    type: file.Archive
                    scanPlaceholders: true
                    fileUri: !value nexus_url
                    targetPath: /etc/local/corporate/share/dist
                    targetPathShared: True
                    createTargetPath: True
        values:
          nexus_url: https://xlfr.s3-eu-west-1.amazonaws.com/PetClinic-2.0.war
          appversion: 1.0.2
      color: '#0099CC'
    riskProfile: Default risk profile
