language: java
notifications:
  slack:
    secure: zEpFwp7e5t0dnvd/BX7gFctTB7ZrZ8gFDPMy/fEAP2jaVr2QZ9QMOBaCiHCqeROUQBD6yGG44KmQ9y7YXVIRD2gVBSk8wPVBWyZy7R3ZJZSXzQc/jCWHysOXAc+7Iik5U/8ZBZDN6Nk07g6hrr0Y1b4xhB9j4mQ3g1pL1DzjQycVP1YMUbauslZkPd1vWGBaLVeehge1XeTgoxQrQKFD+MGzaWzUYQbrmXYV5kLslqC4dOotxuUZFPlZOcgg8+l5/RNNCcTnE/AHTn7L0YeZSILdS+0AI3iAzmyyjrGWB5jux+pE4mxpfLSiG4NMYp/nRjsfKSzEHDZq9C0n4yRzgwDYLRBT4jDpPVKLRg/i4pPXKOpUcTUYsh3jwiNZOmg+htkYTMVR7ryVn/b2KMUu8IRz5NtBYwZKLajfcS8SLYscwvxp1OrwGIFScUN0wGqN+My+zqDwtKZ3xNZRU8yzulo0u/HUykm1K91laiobSFA08KjFBcarBr700z8QDdtRloLokxVVZgc8nWD1aKSoLlMbQIhN0IvXgFiN42eloYM/AvSkr3llsFff+7OiZUE2aWEY26RQj6pBC2pij+6oDceKsB1rXaSBueUG7rqJW9DR1Sw5yNtDjbALYtq6LPg47JWxDVfsg/FrySswGtWmLVQ4azqftktd4rU4RSFd7m0=
deploy:
  provider: releases
  api_key:
    secure: xQEYPccSE2JSEXetc+Ig2Icm9ZXEthZapO+LV92sHhvGRINaIQob+smMYyvlYx+K4DuUNRiyBqAQ904FbhbxUV54ngfB6br3T+5r6tyT8yXRwZvXHrR4lRr4Cyr3TaS+RlgMHbUdw47QjaDmQ7P8EC47LFySXe4C1aMCEKZa4MfKCnPc0L3BBJ84CMHveAsPXcX6JSh/1ZbL3ML7PmtPsM0OnPsP4wDI0+JZvBY8lONR8+Loi4n3YyOBJIXLhoDm/e1qiZzlCZ0WeOqEP1+LSNLsOLRzhEiIgal9W+I9EfcUDF+q10lcHmOQdsc4ER3yLZXPV2VwFTMdlY61vszoetA8BoRkT2mnlkokBZhCIcK3E98CTRwDNrJfAQ0cN013nV8VBRGV+KGysUmw/yUzf0H+vdsL2xLvxx/qvSDgmiClyhtAhkpOiZD/Fwwlo43fLe/9T5yN12X0eBKUHffB42fC+BsHFcurzWZ+MImANyJEQSW0GXAmVG0/vNG7TVDXVtOM4sUwyo357Tomg7tm3HRlHL4oQ7irJB15qViktGYVUea/FUmWpQEWJQxR6E1WnuG41DX8ufeWB5UG+PFOQD0x3sZCy0X08QB9aoWvKglN9QFuzxKER1uWSt4aIRMXQ033bNzolQ+BRBUXr5Du//IeEmhti9SvxYUkR9UtBZY=
  file: lglg
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-devops-as-code-plugin
